items:
  - name: 'Ghost'
    local:
      cmd: ghost
      args: version --no-color --no-prompt
      work_dir: /var/www/olegtarasov.me
      processors:
        - regex: '^Ghost version:\s(.*?)\s.*'
    remote:
      cmd: ghost
      args: check-update --no-prompt --no-color
      work_dir: /var/www/olegtarasov.me
      processors:
        - regex: '^Latest version:\s(.*)$'