items:
  - name: 'Ghost'
    local:
      cmd: ghost
      args: version --no-color --no-prompt
      work_dir: /var/www/olegtarasov.me
      processors:
        - regex: '^Ghost version:\s(.*?)\s.*'
    remote:
      cmd: ghost
      args: check-update --no-prompt --no-color
      work_dir: /var/www/olegtarasov.me
      processors:
        - regex: '^Latest version:\s(.*)$'
  - name: 'vaultwarden'
    local:
      cmd: docker
      args: exec vaultwarden ./vaultwarden -v
      processors:
        - regex: '^vaultwarden\s(.*)'
    remote:
      cmd: gh
      args: api repos/dani-garcia/vaultwarden/releases/latest -q ".tag_name"
  - name: 'vaultwarden-backup'
    local:
      cmd: bash
      args: -c "docker inspect vaultwarden_backup | jq -r '.[0].Image' | xargs docker image inspect | jq -r '.[0].RepoTags[0]'"
      processors:
        - regex: 'vaultwarden-backup:(.*)'
    remote:
      cmd: gh
      args: api repos/ttionya/vaultwarden-backup/releases/latest -q ".tag_name"
      processors:
        - regex: 'v(.*)'
  - name: 'Mailinabox'
    local:
      cmd: curl
      args: -s -X GET "https://box.olegtarasov.email/admin/system/version" -u "!secret(mib_api_login):!secret(mib_api_key)"
      processors:
        - replace: '$1.0.0'
          regex: '^v(.*)'
    remote:
      cmd: curl
      args: -s -X POST "https://box.olegtarasov.email/admin/system/latest-upstream-version" -u "!secret(mib_api_login):!secret(mib_api_key)"
      processors:
        - replace: '$1.0.0'
          regex: '^v(.*)'