items:
  - name: 'btop'
    local:
      cmd: btop
      args: -v
      processors:
        - regex: ':\s(.*)'
    remote:
      cmd: gh
      args: api repos/aristocratos/btop/releases/latest -q ".tag_name"
      processors:
        - regex: 'v(.*)'