name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        rid: [osx-arm64, osx-x64, linux-x64, linux-arm64, win-x64, win-arm64]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Create output dir
        run: mkdir output
      - name: Build
        run: dotnet publish InfraTool/InfraTool.csproj -c Release -r ${{ matrix.rid }} --self-contained false -o output
      - if: "!startsWith(matrix.rid, 'win-')"
        run: mv output/InfraTool output/infratool
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          command: mkdir -p output
          directory: output
          filename: ../infratool-${{ matrix.rid }}.zip
          exclusions: "*.yaml *.json *.pdb *.config"
      - uses: actions/upload-artifact@v4
        with:
          name: infratool-${{ matrix.rid }}.zip
          path: infratool-${{ matrix.rid }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*"
